browser-profiles:
  time-zones:
    - "America/New_York"
    - "America/Chicago"
    - "America/Denver"
    - "America/Los_Angeles"
    - "America/Phoenix"

  user-agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
    - "Mozilla/5.0 (Windows NT 11.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.117 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/116.0.1938.81"

  view-ports:
    - [1366, 768]
    - [1280, 720]
    - [1280, 800]

  device-scale-factors: [1.0, 1.25, 1.5, 1.75, 2.0]

  color-scheme: ["LIGHT", "DARK"]
